model_name: "vanilla_vae" # "InfoVAE" or "vanilla_vae"
model:
  capacity: [2, 8, 16] # [32, 64, 128, 256, 512]
  kernel_size: 4
  channels: 5
  extra_layer: True
  depth_input: True
data_params:
  clustering_params:
    n_batches: 50
  frequencies: [18, 38, 120, 200]
  variational_beta: [1.0] #[0.1, 1.0, 2.0, 5.0, 10.0]
  dev: 1 # Set Cuda device number here, e.g. "dev=2".
  window_dim: 64
  batch_size: 64
  lr: 0.0001
  log_step: 30
  iterations: 3000
  path_model_params_load: "" # Set path to load pre-trained model params (only required if load_pre_trained==True).
  path_model_params_save: "/acoustic/vae_trained.pt" # Insert path, e.g. "/nr/project/bild/Cogmar/usr/obr/model/paper_v2_heave_2.pt",
  partition: "year"
  load_pre_trained: False
  save_model_params: True
  verbose: True
  num_workers: 0
  recon_criterion: "BCE"
  base_figure_dir: "output/info_vae_figures"
